src/Entity/Target.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Target
 *
 * @ORM\Table(name="target")
 * @ORM\Entity
 */
class Target
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="objective_ref", type="string", length=10, nullable=false)
     */
    private $objectiveRef;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="string", length=10, nullable=false)
     */
    private $status;

    /**
     * @var string|null
     *
     * @ORM\Column(name="impact_area", type="string", length=25, nullable=true)
     */
    private $impactArea;

    /**
     * @var string|null
     *
     * @ORM\Column(name="objective", type="string", length=500, nullable=true)
     */
    private $objective;

    /**
     * @var string|null
     *
     * @ORM\Column(name="baseline", type="string", length=100, nullable=true)
     */
    private $baseline;

    /**
     * @var string
     *
     * @ORM\Column(name="owner", type="string", length=50, nullable=false)
     */
    private $owner;

    /**
     * @var string
     *
     * @ORM\Column(name="performance_indicator", type="string", length=500, nullable=false)
     */
    private $performance_indicator;

    /**
     * @var string
     *
     * @ORM\Column(name="target", type="string", length=500, nullable=false)
     */
    private $target;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $target_date;

    /**
     * @ORM\Column(name="target_2021", type="string", length=500, nullable=true)
     */
    private $target_2021;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year_2017_2018;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year_2018_2019;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year_2019_2020;

    /**
     * @return string
     */
    public function getPerformanceIndicator(): string
    {
        return $this->performance_indicator;
    }

    /**
     * @param string $performance_indicator
     */
    public function setPerformanceIndicator(string $performance_indicator): void
    {
        $this->performance_indicator = $performance_indicator;
    }

    /**
     * @return string
     */
    public function getTarget(): string
    {
        return $this->target;
    }

    /**
     * @param string $target
     */
    public function setTarget(string $target): void
    {
        $this->target = $target;
    }

    /**
     * @return mixed
     */
    public function getTargetDate()
    {
        return $this->target_date;
    }

    /**
     * @param mixed $target_date
     */
    public function setTargetDate($target_date): void
    {
        $this->target_date = $target_date;
    }

    /**
     * @return mixed
     */
    public function getTarget2021()
    {
        return $this->target_2021;
    }

    /**
     * @param mixed $target_2021
     */
    public function setTarget2021($target_2021): void
    {
        $this->target_2021 = $target_2021;
    }




    /**
     * @return mixed
     */
    public function getYear20172018()
    {
        return $this->year_2017_2018;
    }

    /**
     * @param mixed $year_2017_2018
     */
    public function setYear20172018($year_2017_2018): void
    {
        $this->year_2017_2018 = $year_2017_2018;
    }

    /**
     * @return mixed
     */
    public function getYear20182019()
    {
        return $this->year_2018_2019;
    }

    /**
     * @param mixed $year_2018_2019
     */
    public function setYear20182019($year_2018_2019): void
    {
        $this->year_2018_2019 = $year_2018_2019;
    }

    /**
     * @return mixed
     */
    public function getYear20192020()
    {
        return $this->year_2019_2020;
    }

    /**
     * @param mixed $year_2019_2020
     */
    public function setYear20192020($year_2019_2020): void
    {
        $this->year_2019_2020 = $year_2019_2020;
    }

    /**
     * @return string
     */
    public function getProgressComments(): string
    {
        return $this->progress_comments;
    }

    /**
     * @param string $progress_comments
     */
    public function setProgressComments(string $progress_comments): void
    {
        $this->progress_comments = $progress_comments;
    }


    /**
     * @var string
     *
     * @ORM\Column(name="progress_comments", type="string", length=500, nullable=true)
     */
    private $progress_comments;


    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }



    /**
     * @return string
     */
    public function getObjectiveRef(): string
    {
        return $this->objectiveRef;
    }

    /**
     * @param string $objectiveRef
     */
    public function setObjectiveRef(string $objectiveRef): void
    {
        $this->objectiveRef = $objectiveRef;
    }

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * @return string|null
     */
    public function getImpactArea(): ?string
    {
        return $this->impactArea;
    }

    /**
     * @param string|null $impactArea
     */
    public function setImpactArea(?string $impactArea): void
    {
        $this->impactArea = $impactArea;
    }

    /**
     * @return string|null
     */
    public function getObjective(): ?string
    {
        return $this->objective;
    }

    /**
     * @param string|null $objective
     */
    public function setObjective(?string $objective): void
    {
        $this->objective = $objective;
    }

    /**
     * @return string|null
     */
    public function getBaseline(): ?string
    {
        return $this->baseline;
    }

    /**
     * @param string|null $baseline
     */
    public function setBaseline(?string $baseline): void
    {
        $this->baseline = $baseline;
    }

    /**
     * @return string
     */
    public function getOwner(): string
    {
        return $this->owner;
    }

    /**
     * @param string $owner
     */
    public function setOwner(string $owner): void
    {
        $this->owner = $owner;
    }






}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Target;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

class DashboardController extends AbstractController
{

    #[Route('/dashboard', name: 'dashboard')]
    public function dashboard(ChartBuilderInterface $chartBuilder)
    {
        $repository = $this->getDoctrine()->getRepository(Target::class);

        $targetData = $repository->findAll();

        return $this->render('dashboard/index.html.twig', [
            'targetData' => $targetData
        ]);
    }

    #[Route('/dashboard/chart/{id}', name: 'chart')]
    public function chart(ChartBuilderInterface $chartBuilder, $id)
    {
        $repository = $this->getDoctrine()->getRepository(Target::class);

        $targetData = $repository->find($id);

        $data2017 = $targetData->getYear20172018();
//        dd($data2017);
        $data2018 = $targetData->getYear20182019();
        $data2019 = $targetData->getYear20192020();

        $chart = $chartBuilder->createChart(Chart::TYPE_PIE);
        $chart->setData([
            'title' => "Objective",
            'labels' => ['2017', '2018', '2019'],
            'datasets' => [[
                'label' => 'My First Dataset',
                'data' => [$data2017, $data2018, $data2019],
                'backgroundColor' => [
                    'rgb(255, 99, 132)',
                    'rgb(54, 162, 235)',
                    'rgb(255, 205, 86)'
                ]
            ]]
        ]);
        $chart->setOptions([
            'title' => [
                'display' => true,
                'text' => 'Custom chart title'
            ]
        ]);

        return $this->render('dashboard/chart.html.twig', [
            'chart' => $chart,
            'targetData' => $targetData
        ]);

    }
}

templates/dashboard/chart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Target Chart{% endblock %}

{% block body %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">
            <div class="row">
                <div class="card">
                </div>
                <div class="col-3 mt-4">
                    <h1>{{ targetdata.objectiveRef }}</h1>
                    {{ render_chart(chart) }}
                </div>
            </div>
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{ recyclingData.building }}</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped order-column" id="dataTable">
                            <thead class="text-center">
                            <tr>
                                <th>Objective Ref</th>
                                <th>Status</th>
                                <th>Impact Area</th>
                                <th>Objective</th>
                                <th>Baseline</th>
                                <th>Owner</th>
                                <th>Performance Indicator</th>
                                <th>Target</th>
                                <th>Target 2021</th>
                                <th>2017-2018</th>
                                <th>2018-2019</th>
                                <th>2019-2020</th>
                                <th>Progress Comments</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{ targetData.objectiveRef }}</a></td>
                                <td>{{ targetData.status }}</td>
                                <td>{{ targetData.impactArea }}</td>
                                <td>{{ targetData.objective }}</td>
                                <td>{{ targetData.baseline }}</td>
                                <td>{{ targetData.owner }}</td>
                                <td>{{ targetData.performanceIndicator }}</td>
                                <td>{{ targetData.target }}</td>
                                <td>{{ targetData.target2021 }}</td>
                                <td>{{ targetData.year20172018 }}</td>
                                <td>{{ targetData.year20182019 }}</td>
                                <td>{{ targetData.year20192020 }}</td>
                                <td>{{ targetData.progressComments }}</td>
                            </tr>


                            </tbody>
                        </table>
                    </div>
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"></h6>
                </div>
                <div class="card-body">
                    <button><a href="{{ path('dashboard') }}">Back to all objectives data</a></button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Objectives{% endblock %}

{% block body %}
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Objectives</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped order-column" id="dataTable">
                            <thead class="text-center">
                            <tr>
                                <th>Objective Ref</th>
                                <th>Status</th>
                                <th>Impact Area</th>
                                <th>Objective</th>
                                <th>Baseline</th>
                                <th>Owner</th>
                                <th>Performance Indicator</th>
                                <th>Target</th>
                                <th>Target 2021</th>
                                <th>2017-2018</th>
                                <th>2018-2019</th>
                                <th>2019-2020</th>
                                <th>Progress Comments</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for data in targetData %}
                                <tr>
                                    <td><a href="{{ path('chart', {id:data.id}) }}">{{ data.objectiveRef }}</a></td>
                                    <td>{{ data.status }}</td>
                                    <td>{{ data.impactArea }}</td>
                                    <td>{{ data.objective }}</td>
                                    <td>{{ data.baseline }}</td>
                                    <td>{{ data.owner }}</td>
                                    <td>{{ data.performanceIndicator }}</td>
                                    <td>{{ data.target }}</td>
                                    <td>{{ data.target2021 }}</td>
                                    <td>{{ data.year20172018 }}</td>
                                    <td>{{ data.year20182019 }}</td>
                                    <td>{{ data.year20192020 }}</td>
                                    <td>{{ data.progressComments }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}